# Generated by Django 5.2.15 on 2026-07-01 15:39

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(blank=True, max_length=200, verbose_name='Diplôme')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name="Domaine d'études")),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name="Années d'expérience")),
                ('current_position', models.CharField(blank=True, max_length=200, verbose_name='Poste actuel')),
                ('linkedin', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True, verbose_name='Résumé / bio')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to=apps.accounts.models.profile_cv_upload_path)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
