# Generated by Django 5.2.15 on 2026-06-25 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list, help_text='Liste de compétences requises')),
                ('min_experience', models.PositiveIntegerField(default=0, help_text="Années d'expérience minimum")),
                ('required_degree', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(default='Kinshasa', max_length=100)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('closed', 'Clôturée')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='jobs.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
