# Generated by Django 5.2.15 on 2026-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='image_key',
            field=models.CharField(blank=True, help_text='Clé image frontend (commercial, logistique, it, etc.)', max_length=50),
        ),
    ]
